version: 2
project_name: meta.go

before:
  hooks:
    - go mod verify

builds:
  - id: meta
    main: ./cmd/meta
    binary: meta
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X go.mewis.me/meta.go.Version={{ .Version }} -X go.mewis.me/meta.go.Commit={{ .Commit }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
upx:
  - ids:
      - meta
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    compress: best
  - ids:
      - meta
    goos:
      - windows
    goarch:
      - amd64
    compress: best

archives:
  - id: meta
    ids:
      - meta
    name_template: "meta_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - THIRD_PARTY_LICENSES.md
      - docs/*
checksum:
  name_template: "meta_{{ .Version }}_checksums.txt"
  algorithm: sha256

sboms:
  - id: archives
    artifacts: archive
  - id: binaries
    artifacts: binary

changelog:
  use: git
  sort: asc

release:
  draft: false
  prerelease: auto
