# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from meta.v1 import e2ee_pb2 as meta_dot_v1_dot_e2ee__pb2


class E2EEServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendText = channel.unary_unary(
                '/meta.v1.E2EEService/SendText',
                request_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceSendTextRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceSendTextResponse.FromString,
                _registered_method=True)
        self.SendMedia = channel.stream_unary(
                '/meta.v1.E2EEService/SendMedia',
                request_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceSendMediaRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceSendMediaResponse.FromString,
                _registered_method=True)
        self.DownloadMedia = channel.unary_stream(
                '/meta.v1.E2EEService/DownloadMedia',
                request_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceDownloadMediaRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceDownloadMediaResponse.FromString,
                _registered_method=True)
        self.React = channel.unary_unary(
                '/meta.v1.E2EEService/React',
                request_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceReactRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceReactResponse.FromString,
                _registered_method=True)
        self.Edit = channel.unary_unary(
                '/meta.v1.E2EEService/Edit',
                request_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceEditRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceEditResponse.FromString,
                _registered_method=True)
        self.Unsend = channel.unary_unary(
                '/meta.v1.E2EEService/Unsend',
                request_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceUnsendRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceUnsendResponse.FromString,
                _registered_method=True)
        self.SetTyping = channel.unary_unary(
                '/meta.v1.E2EEService/SetTyping',
                request_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceSetTypingRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceSetTypingResponse.FromString,
                _registered_method=True)
        self.MarkRead = channel.unary_unary(
                '/meta.v1.E2EEService/MarkRead',
                request_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceMarkReadRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceMarkReadResponse.FromString,
                _registered_method=True)


class E2EEServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMedia(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadMedia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def React(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Edit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTyping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_E2EEServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendText': grpc.unary_unary_rpc_method_handler(
                    servicer.SendText,
                    request_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceSendTextRequest.FromString,
                    response_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceSendTextResponse.SerializeToString,
            ),
            'SendMedia': grpc.stream_unary_rpc_method_handler(
                    servicer.SendMedia,
                    request_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceSendMediaRequest.FromString,
                    response_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceSendMediaResponse.SerializeToString,
            ),
            'DownloadMedia': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadMedia,
                    request_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceDownloadMediaRequest.FromString,
                    response_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceDownloadMediaResponse.SerializeToString,
            ),
            'React': grpc.unary_unary_rpc_method_handler(
                    servicer.React,
                    request_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceReactRequest.FromString,
                    response_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceReactResponse.SerializeToString,
            ),
            'Edit': grpc.unary_unary_rpc_method_handler(
                    servicer.Edit,
                    request_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceEditRequest.FromString,
                    response_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceEditResponse.SerializeToString,
            ),
            'Unsend': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsend,
                    request_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceUnsendRequest.FromString,
                    response_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceUnsendResponse.SerializeToString,
            ),
            'SetTyping': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTyping,
                    request_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceSetTypingRequest.FromString,
                    response_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceSetTypingResponse.SerializeToString,
            ),
            'MarkRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkRead,
                    request_deserializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceMarkReadRequest.FromString,
                    response_serializer=meta_dot_v1_dot_e2ee__pb2.E2EEServiceMarkReadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meta.v1.E2EEService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meta.v1.E2EEService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class E2EEService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.E2EEService/SendText',
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceSendTextRequest.SerializeToString,
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceSendTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMedia(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/meta.v1.E2EEService/SendMedia',
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceSendMediaRequest.SerializeToString,
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceSendMediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/meta.v1.E2EEService/DownloadMedia',
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceDownloadMediaRequest.SerializeToString,
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceDownloadMediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def React(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.E2EEService/React',
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceReactRequest.SerializeToString,
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceReactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Edit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.E2EEService/Edit',
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceEditRequest.SerializeToString,
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceEditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unsend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.E2EEService/Unsend',
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceUnsendRequest.SerializeToString,
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceUnsendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTyping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.E2EEService/SetTyping',
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceSetTypingRequest.SerializeToString,
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceSetTypingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.E2EEService/MarkRead',
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceMarkReadRequest.SerializeToString,
            meta_dot_v1_dot_e2ee__pb2.E2EEServiceMarkReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
