# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from meta.v1 import facebook_pb2 as meta_dot_v1_dot_facebook__pb2


class FacebookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/meta.v1.FacebookService/GetUser',
                request_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceGetUserRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceGetUserResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/meta.v1.FacebookService/Search',
                request_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSearchRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSearchResponse.FromString,
                _registered_method=True)
        self.ListNotifications = channel.unary_unary(
                '/meta.v1.FacebookService/ListNotifications',
                request_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceListNotificationsRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceListNotificationsResponse.FromString,
                _registered_method=True)
        self.SetBio = channel.unary_unary(
                '/meta.v1.FacebookService/SetBio',
                request_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSetBioRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSetBioResponse.FromString,
                _registered_method=True)
        self.CreateAdditionalProfile = channel.unary_unary(
                '/meta.v1.FacebookService/CreateAdditionalProfile',
                request_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceCreateAdditionalProfileRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceCreateAdditionalProfileResponse.FromString,
                _registered_method=True)
        self.Unfriend = channel.unary_unary(
                '/meta.v1.FacebookService/Unfriend',
                request_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceUnfriendRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceUnfriendResponse.FromString,
                _registered_method=True)
        self.SetBlocked = channel.unary_unary(
                '/meta.v1.FacebookService/SetBlocked',
                request_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSetBlockedRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSetBlockedResponse.FromString,
                _registered_method=True)
        self.CreatePost = channel.unary_unary(
                '/meta.v1.FacebookService/CreatePost',
                request_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceCreatePostRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceCreatePostResponse.FromString,
                _registered_method=True)
        self.ArchivePost = channel.unary_unary(
                '/meta.v1.FacebookService/ArchivePost',
                request_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceArchivePostRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceArchivePostResponse.FromString,
                _registered_method=True)
        self.DeletePost = channel.unary_unary(
                '/meta.v1.FacebookService/DeletePost',
                request_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceDeletePostRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceDeletePostResponse.FromString,
                _registered_method=True)
        self.CreateMarketplaceListing = channel.unary_unary(
                '/meta.v1.FacebookService/CreateMarketplaceListing',
                request_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceCreateMarketplaceListingRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceCreateMarketplaceListingResponse.FromString,
                _registered_method=True)
        self.GetMarketplaceListing = channel.unary_unary(
                '/meta.v1.FacebookService/GetMarketplaceListing',
                request_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceGetMarketplaceListingRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceGetMarketplaceListingResponse.FromString,
                _registered_method=True)
        self.SetProfessionalMode = channel.unary_unary(
                '/meta.v1.FacebookService/SetProfessionalMode',
                request_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSetProfessionalModeRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSetProfessionalModeResponse.FromString,
                _registered_method=True)


class FacebookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNotifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAdditionalProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unfriend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBlocked(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchivePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMarketplaceListing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarketplaceListing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProfessionalMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FacebookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceGetUserRequest.FromString,
                    response_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceGetUserResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSearchRequest.FromString,
                    response_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSearchResponse.SerializeToString,
            ),
            'ListNotifications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNotifications,
                    request_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceListNotificationsRequest.FromString,
                    response_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceListNotificationsResponse.SerializeToString,
            ),
            'SetBio': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBio,
                    request_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSetBioRequest.FromString,
                    response_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSetBioResponse.SerializeToString,
            ),
            'CreateAdditionalProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAdditionalProfile,
                    request_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceCreateAdditionalProfileRequest.FromString,
                    response_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceCreateAdditionalProfileResponse.SerializeToString,
            ),
            'Unfriend': grpc.unary_unary_rpc_method_handler(
                    servicer.Unfriend,
                    request_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceUnfriendRequest.FromString,
                    response_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceUnfriendResponse.SerializeToString,
            ),
            'SetBlocked': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBlocked,
                    request_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSetBlockedRequest.FromString,
                    response_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSetBlockedResponse.SerializeToString,
            ),
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceCreatePostRequest.FromString,
                    response_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceCreatePostResponse.SerializeToString,
            ),
            'ArchivePost': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchivePost,
                    request_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceArchivePostRequest.FromString,
                    response_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceArchivePostResponse.SerializeToString,
            ),
            'DeletePost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePost,
                    request_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceDeletePostRequest.FromString,
                    response_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceDeletePostResponse.SerializeToString,
            ),
            'CreateMarketplaceListing': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMarketplaceListing,
                    request_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceCreateMarketplaceListingRequest.FromString,
                    response_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceCreateMarketplaceListingResponse.SerializeToString,
            ),
            'GetMarketplaceListing': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketplaceListing,
                    request_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceGetMarketplaceListingRequest.FromString,
                    response_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceGetMarketplaceListingResponse.SerializeToString,
            ),
            'SetProfessionalMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProfessionalMode,
                    request_deserializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSetProfessionalModeRequest.FromString,
                    response_serializer=meta_dot_v1_dot_facebook__pb2.FacebookServiceSetProfessionalModeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meta.v1.FacebookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meta.v1.FacebookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FacebookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.FacebookService/GetUser',
            meta_dot_v1_dot_facebook__pb2.FacebookServiceGetUserRequest.SerializeToString,
            meta_dot_v1_dot_facebook__pb2.FacebookServiceGetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.FacebookService/Search',
            meta_dot_v1_dot_facebook__pb2.FacebookServiceSearchRequest.SerializeToString,
            meta_dot_v1_dot_facebook__pb2.FacebookServiceSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.FacebookService/ListNotifications',
            meta_dot_v1_dot_facebook__pb2.FacebookServiceListNotificationsRequest.SerializeToString,
            meta_dot_v1_dot_facebook__pb2.FacebookServiceListNotificationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.FacebookService/SetBio',
            meta_dot_v1_dot_facebook__pb2.FacebookServiceSetBioRequest.SerializeToString,
            meta_dot_v1_dot_facebook__pb2.FacebookServiceSetBioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAdditionalProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.FacebookService/CreateAdditionalProfile',
            meta_dot_v1_dot_facebook__pb2.FacebookServiceCreateAdditionalProfileRequest.SerializeToString,
            meta_dot_v1_dot_facebook__pb2.FacebookServiceCreateAdditionalProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unfriend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.FacebookService/Unfriend',
            meta_dot_v1_dot_facebook__pb2.FacebookServiceUnfriendRequest.SerializeToString,
            meta_dot_v1_dot_facebook__pb2.FacebookServiceUnfriendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBlocked(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.FacebookService/SetBlocked',
            meta_dot_v1_dot_facebook__pb2.FacebookServiceSetBlockedRequest.SerializeToString,
            meta_dot_v1_dot_facebook__pb2.FacebookServiceSetBlockedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.FacebookService/CreatePost',
            meta_dot_v1_dot_facebook__pb2.FacebookServiceCreatePostRequest.SerializeToString,
            meta_dot_v1_dot_facebook__pb2.FacebookServiceCreatePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchivePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.FacebookService/ArchivePost',
            meta_dot_v1_dot_facebook__pb2.FacebookServiceArchivePostRequest.SerializeToString,
            meta_dot_v1_dot_facebook__pb2.FacebookServiceArchivePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.FacebookService/DeletePost',
            meta_dot_v1_dot_facebook__pb2.FacebookServiceDeletePostRequest.SerializeToString,
            meta_dot_v1_dot_facebook__pb2.FacebookServiceDeletePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMarketplaceListing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.FacebookService/CreateMarketplaceListing',
            meta_dot_v1_dot_facebook__pb2.FacebookServiceCreateMarketplaceListingRequest.SerializeToString,
            meta_dot_v1_dot_facebook__pb2.FacebookServiceCreateMarketplaceListingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMarketplaceListing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.FacebookService/GetMarketplaceListing',
            meta_dot_v1_dot_facebook__pb2.FacebookServiceGetMarketplaceListingRequest.SerializeToString,
            meta_dot_v1_dot_facebook__pb2.FacebookServiceGetMarketplaceListingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetProfessionalMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.FacebookService/SetProfessionalMode',
            meta_dot_v1_dot_facebook__pb2.FacebookServiceSetProfessionalModeRequest.SerializeToString,
            meta_dot_v1_dot_facebook__pb2.FacebookServiceSetProfessionalModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
