# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meta/v1/health.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'meta/v1/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14meta/v1/health.proto\x12\x07meta.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x03\n\x0eHealthSnapshot\x12\x32\n\x07regular\x18\x01 \x01(\x0e\x32\x18.meta.v1.ConnectionStateR\x07regular\x12,\n\x04\x65\x32\x65\x65\x18\x02 \x01(\x0e\x32\x18.meta.v1.ConnectionStateR\x04\x65\x32\x65\x65\x12\'\n\x0freconnect_count\x18\x03 \x01(\x04R\x0ereconnectCount\x12;\n\x1a\x65ngine_dropped_event_count\x18\x04 \x01(\x04R\x17\x65ngineDroppedEventCount\x12\x43\n\x1esubscriber_dropped_event_count\x18\x05 \x01(\x04R\x1bsubscriberDroppedEventCount\x12L\n\x14last_successful_send\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x12lastSuccessfulSend\x12=\n\x0clast_receive\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0blastReceive\x12.\n\x13last_error_category\x18\x08 \x01(\tR\x11lastErrorCategory*\xb4\x01\n\x0f\x43onnectionState\x12 \n\x1c\x43ONNECTION_STATE_UNSPECIFIED\x10\x00\x12!\n\x1d\x43ONNECTION_STATE_DISCONNECTED\x10\x01\x12\x1f\n\x1b\x43ONNECTION_STATE_CONNECTING\x10\x02\x12\x1e\n\x1a\x43ONNECTION_STATE_CONNECTED\x10\x03\x12\x1b\n\x17\x43ONNECTION_STATE_FAILED\x10\x04\x42+Z)go.mewis.me/meta.go/gen/go/meta/v1;metav1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meta.v1.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)go.mewis.me/meta.go/gen/go/meta/v1;metav1'
  _globals['_CONNECTIONSTATE']._serialized_start=544
  _globals['_CONNECTIONSTATE']._serialized_end=724
  _globals['_HEALTHSNAPSHOT']._serialized_start=67
  _globals['_HEALTHSNAPSHOT']._serialized_end=541
# @@protoc_insertion_point(module_scope)
