# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from meta.v1 import messenger_pb2 as meta_dot_v1_dot_messenger__pb2


class MessengerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/meta.v1.MessengerService/Send',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SendRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SendResponse.FromString,
                _registered_method=True)
        self.Upload = channel.stream_unary(
                '/meta.v1.MessengerService/Upload',
                request_serializer=meta_dot_v1_dot_messenger__pb2.UploadRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.Forward = channel.unary_unary(
                '/meta.v1.MessengerService/Forward',
                request_serializer=meta_dot_v1_dot_messenger__pb2.ForwardRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.ShareContact = channel.unary_unary(
                '/meta.v1.MessengerService/ShareContact',
                request_serializer=meta_dot_v1_dot_messenger__pb2.ShareContactRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.ShareContactResponse.FromString,
                _registered_method=True)
        self.React = channel.unary_unary(
                '/meta.v1.MessengerService/React',
                request_serializer=meta_dot_v1_dot_messenger__pb2.ReactRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.ReactResponse.FromString,
                _registered_method=True)
        self.Edit = channel.unary_unary(
                '/meta.v1.MessengerService/Edit',
                request_serializer=meta_dot_v1_dot_messenger__pb2.EditRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.EditResponse.FromString,
                _registered_method=True)
        self.Unsend = channel.unary_unary(
                '/meta.v1.MessengerService/Unsend',
                request_serializer=meta_dot_v1_dot_messenger__pb2.UnsendRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.UnsendResponse.FromString,
                _registered_method=True)
        self.SetTyping = channel.unary_unary(
                '/meta.v1.MessengerService/SetTyping',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SetTypingRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SetTypingResponse.FromString,
                _registered_method=True)
        self.MarkRead = channel.unary_unary(
                '/meta.v1.MessengerService/MarkRead',
                request_serializer=meta_dot_v1_dot_messenger__pb2.MarkReadRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.MarkReadResponse.FromString,
                _registered_method=True)
        self.ListMessageRequests = channel.unary_unary(
                '/meta.v1.MessengerService/ListMessageRequests',
                request_serializer=meta_dot_v1_dot_messenger__pb2.ListMessageRequestsRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.ListMessageRequestsResponse.FromString,
                _registered_method=True)
        self.ListThemes = channel.unary_unary(
                '/meta.v1.MessengerService/ListThemes',
                request_serializer=meta_dot_v1_dot_messenger__pb2.ListThemesRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.ListThemesResponse.FromString,
                _registered_method=True)
        self.FindTheme = channel.unary_unary(
                '/meta.v1.MessengerService/FindTheme',
                request_serializer=meta_dot_v1_dot_messenger__pb2.FindThemeRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.FindThemeResponse.FromString,
                _registered_method=True)
        self.SetTheme = channel.unary_unary(
                '/meta.v1.MessengerService/SetTheme',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SetThemeRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SetThemeResponse.FromString,
                _registered_method=True)
        self.GetCurrentNote = channel.unary_unary(
                '/meta.v1.MessengerService/GetCurrentNote',
                request_serializer=meta_dot_v1_dot_messenger__pb2.GetCurrentNoteRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.GetCurrentNoteResponse.FromString,
                _registered_method=True)
        self.CreateNote = channel.unary_unary(
                '/meta.v1.MessengerService/CreateNote',
                request_serializer=meta_dot_v1_dot_messenger__pb2.CreateNoteRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.CreateNoteResponse.FromString,
                _registered_method=True)
        self.DeleteNote = channel.unary_unary(
                '/meta.v1.MessengerService/DeleteNote',
                request_serializer=meta_dot_v1_dot_messenger__pb2.DeleteNoteRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.DeleteNoteResponse.FromString,
                _registered_method=True)
        self.RecreateNote = channel.unary_unary(
                '/meta.v1.MessengerService/RecreateNote',
                request_serializer=meta_dot_v1_dot_messenger__pb2.RecreateNoteRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.RecreateNoteResponse.FromString,
                _registered_method=True)
        self.SetRestricted = channel.unary_unary(
                '/meta.v1.MessengerService/SetRestricted',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SetRestrictedRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SetRestrictedResponse.FromString,
                _registered_method=True)
        self.SetMessageBlocked = channel.unary_unary(
                '/meta.v1.MessengerService/SetMessageBlocked',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SetMessageBlockedRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SetMessageBlockedResponse.FromString,
                _registered_method=True)
        self.ListThreads = channel.unary_unary(
                '/meta.v1.MessengerService/ListThreads',
                request_serializer=meta_dot_v1_dot_messenger__pb2.ListThreadsRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.ListThreadsResponse.FromString,
                _registered_method=True)
        self.GetThread = channel.unary_unary(
                '/meta.v1.MessengerService/GetThread',
                request_serializer=meta_dot_v1_dot_messenger__pb2.GetThreadRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.GetThreadResponse.FromString,
                _registered_method=True)
        self.CreatePoll = channel.unary_unary(
                '/meta.v1.MessengerService/CreatePoll',
                request_serializer=meta_dot_v1_dot_messenger__pb2.CreatePollRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.CreatePollResponse.FromString,
                _registered_method=True)
        self.VotePoll = channel.unary_unary(
                '/meta.v1.MessengerService/VotePoll',
                request_serializer=meta_dot_v1_dot_messenger__pb2.VotePollRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.VotePollResponse.FromString,
                _registered_method=True)
        self.ListPinnedMessages = channel.unary_unary(
                '/meta.v1.MessengerService/ListPinnedMessages',
                request_serializer=meta_dot_v1_dot_messenger__pb2.ListPinnedMessagesRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.ListPinnedMessagesResponse.FromString,
                _registered_method=True)
        self.GetPollDetails = channel.unary_unary(
                '/meta.v1.MessengerService/GetPollDetails',
                request_serializer=meta_dot_v1_dot_messenger__pb2.GetPollDetailsRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.GetPollDetailsResponse.FromString,
                _registered_method=True)
        self.SearchMessages = channel.unary_unary(
                '/meta.v1.MessengerService/SearchMessages',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SearchMessagesRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SearchMessagesResponse.FromString,
                _registered_method=True)
        self.MuteThread = channel.unary_unary(
                '/meta.v1.MessengerService/MuteThread',
                request_serializer=meta_dot_v1_dot_messenger__pb2.MuteThreadRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.MuteThreadResponse.FromString,
                _registered_method=True)
        self.MuteThreadCalls = channel.unary_unary(
                '/meta.v1.MessengerService/MuteThreadCalls',
                request_serializer=meta_dot_v1_dot_messenger__pb2.MuteThreadCallsRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.MuteThreadCallsResponse.FromString,
                _registered_method=True)
        self.SetApprovalMode = channel.unary_unary(
                '/meta.v1.MessengerService/SetApprovalMode',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SetApprovalModeRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SetApprovalModeResponse.FromString,
                _registered_method=True)
        self.SetArchived = channel.unary_unary(
                '/meta.v1.MessengerService/SetArchived',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SetArchivedRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SetArchivedResponse.FromString,
                _registered_method=True)
        self.SetMessagePinned = channel.unary_unary(
                '/meta.v1.MessengerService/SetMessagePinned',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SetMessagePinnedRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SetMessagePinnedResponse.FromString,
                _registered_method=True)
        self.SetThreadPhoto = channel.stream_unary(
                '/meta.v1.MessengerService/SetThreadPhoto',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SetThreadPhotoRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SetThreadPhotoResponse.FromString,
                _registered_method=True)
        self.DeleteThread = channel.unary_unary(
                '/meta.v1.MessengerService/DeleteThread',
                request_serializer=meta_dot_v1_dot_messenger__pb2.DeleteThreadRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.DeleteThreadResponse.FromString,
                _registered_method=True)
        self.CreateDM = channel.unary_unary(
                '/meta.v1.MessengerService/CreateDM',
                request_serializer=meta_dot_v1_dot_messenger__pb2.CreateDMRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.CreateDMResponse.FromString,
                _registered_method=True)
        self.SearchUsers = channel.unary_unary(
                '/meta.v1.MessengerService/SearchUsers',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SearchUsersRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SearchUsersResponse.FromString,
                _registered_method=True)
        self.GetContact = channel.unary_unary(
                '/meta.v1.MessengerService/GetContact',
                request_serializer=meta_dot_v1_dot_messenger__pb2.GetContactRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.GetContactResponse.FromString,
                _registered_method=True)
        self.SetAdmin = channel.unary_unary(
                '/meta.v1.MessengerService/SetAdmin',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SetAdminRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SetAdminResponse.FromString,
                _registered_method=True)
        self.SetThreadName = channel.unary_unary(
                '/meta.v1.MessengerService/SetThreadName',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SetThreadNameRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SetThreadNameResponse.FromString,
                _registered_method=True)
        self.SetThreadEmoji = channel.unary_unary(
                '/meta.v1.MessengerService/SetThreadEmoji',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SetThreadEmojiRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SetThreadEmojiResponse.FromString,
                _registered_method=True)
        self.SetNickname = channel.unary_unary(
                '/meta.v1.MessengerService/SetNickname',
                request_serializer=meta_dot_v1_dot_messenger__pb2.SetNicknameRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_messenger__pb2.SetNicknameResponse.FromString,
                _registered_method=True)


class MessengerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Upload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def React(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Edit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTyping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessageRequests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListThemes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindTheme(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTheme(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecreateNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRestricted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMessageBlocked(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListThreads(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePoll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VotePoll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPinnedMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPollDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MuteThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MuteThreadCalls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetApprovalMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetArchived(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMessagePinned(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetThreadPhoto(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetThreadName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetThreadEmoji(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNickname(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessengerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SendRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SendResponse.SerializeToString,
            ),
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.UploadRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.UploadResponse.SerializeToString,
            ),
            'Forward': grpc.unary_unary_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.ForwardRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.ForwardResponse.SerializeToString,
            ),
            'ShareContact': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareContact,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.ShareContactRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.ShareContactResponse.SerializeToString,
            ),
            'React': grpc.unary_unary_rpc_method_handler(
                    servicer.React,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.ReactRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.ReactResponse.SerializeToString,
            ),
            'Edit': grpc.unary_unary_rpc_method_handler(
                    servicer.Edit,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.EditRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.EditResponse.SerializeToString,
            ),
            'Unsend': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsend,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.UnsendRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.UnsendResponse.SerializeToString,
            ),
            'SetTyping': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTyping,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SetTypingRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SetTypingResponse.SerializeToString,
            ),
            'MarkRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkRead,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.MarkReadRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.MarkReadResponse.SerializeToString,
            ),
            'ListMessageRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessageRequests,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.ListMessageRequestsRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.ListMessageRequestsResponse.SerializeToString,
            ),
            'ListThemes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListThemes,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.ListThemesRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.ListThemesResponse.SerializeToString,
            ),
            'FindTheme': grpc.unary_unary_rpc_method_handler(
                    servicer.FindTheme,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.FindThemeRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.FindThemeResponse.SerializeToString,
            ),
            'SetTheme': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTheme,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SetThemeRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SetThemeResponse.SerializeToString,
            ),
            'GetCurrentNote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentNote,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.GetCurrentNoteRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.GetCurrentNoteResponse.SerializeToString,
            ),
            'CreateNote': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNote,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.CreateNoteRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.CreateNoteResponse.SerializeToString,
            ),
            'DeleteNote': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNote,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.DeleteNoteRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.DeleteNoteResponse.SerializeToString,
            ),
            'RecreateNote': grpc.unary_unary_rpc_method_handler(
                    servicer.RecreateNote,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.RecreateNoteRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.RecreateNoteResponse.SerializeToString,
            ),
            'SetRestricted': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRestricted,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SetRestrictedRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SetRestrictedResponse.SerializeToString,
            ),
            'SetMessageBlocked': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMessageBlocked,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SetMessageBlockedRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SetMessageBlockedResponse.SerializeToString,
            ),
            'ListThreads': grpc.unary_unary_rpc_method_handler(
                    servicer.ListThreads,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.ListThreadsRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.ListThreadsResponse.SerializeToString,
            ),
            'GetThread': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThread,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.GetThreadRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.GetThreadResponse.SerializeToString,
            ),
            'CreatePoll': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePoll,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.CreatePollRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.CreatePollResponse.SerializeToString,
            ),
            'VotePoll': grpc.unary_unary_rpc_method_handler(
                    servicer.VotePoll,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.VotePollRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.VotePollResponse.SerializeToString,
            ),
            'ListPinnedMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPinnedMessages,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.ListPinnedMessagesRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.ListPinnedMessagesResponse.SerializeToString,
            ),
            'GetPollDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPollDetails,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.GetPollDetailsRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.GetPollDetailsResponse.SerializeToString,
            ),
            'SearchMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMessages,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SearchMessagesRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SearchMessagesResponse.SerializeToString,
            ),
            'MuteThread': grpc.unary_unary_rpc_method_handler(
                    servicer.MuteThread,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.MuteThreadRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.MuteThreadResponse.SerializeToString,
            ),
            'MuteThreadCalls': grpc.unary_unary_rpc_method_handler(
                    servicer.MuteThreadCalls,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.MuteThreadCallsRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.MuteThreadCallsResponse.SerializeToString,
            ),
            'SetApprovalMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetApprovalMode,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SetApprovalModeRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SetApprovalModeResponse.SerializeToString,
            ),
            'SetArchived': grpc.unary_unary_rpc_method_handler(
                    servicer.SetArchived,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SetArchivedRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SetArchivedResponse.SerializeToString,
            ),
            'SetMessagePinned': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMessagePinned,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SetMessagePinnedRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SetMessagePinnedResponse.SerializeToString,
            ),
            'SetThreadPhoto': grpc.stream_unary_rpc_method_handler(
                    servicer.SetThreadPhoto,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SetThreadPhotoRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SetThreadPhotoResponse.SerializeToString,
            ),
            'DeleteThread': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteThread,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.DeleteThreadRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.DeleteThreadResponse.SerializeToString,
            ),
            'CreateDM': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDM,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.CreateDMRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.CreateDMResponse.SerializeToString,
            ),
            'SearchUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchUsers,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SearchUsersRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SearchUsersResponse.SerializeToString,
            ),
            'GetContact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContact,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.GetContactRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.GetContactResponse.SerializeToString,
            ),
            'SetAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAdmin,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SetAdminRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SetAdminResponse.SerializeToString,
            ),
            'SetThreadName': grpc.unary_unary_rpc_method_handler(
                    servicer.SetThreadName,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SetThreadNameRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SetThreadNameResponse.SerializeToString,
            ),
            'SetThreadEmoji': grpc.unary_unary_rpc_method_handler(
                    servicer.SetThreadEmoji,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SetThreadEmojiRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SetThreadEmojiResponse.SerializeToString,
            ),
            'SetNickname': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNickname,
                    request_deserializer=meta_dot_v1_dot_messenger__pb2.SetNicknameRequest.FromString,
                    response_serializer=meta_dot_v1_dot_messenger__pb2.SetNicknameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meta.v1.MessengerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meta.v1.MessengerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessengerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/Send',
            meta_dot_v1_dot_messenger__pb2.SendRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/meta.v1.MessengerService/Upload',
            meta_dot_v1_dot_messenger__pb2.UploadRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/Forward',
            meta_dot_v1_dot_messenger__pb2.ForwardRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/ShareContact',
            meta_dot_v1_dot_messenger__pb2.ShareContactRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.ShareContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def React(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/React',
            meta_dot_v1_dot_messenger__pb2.ReactRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.ReactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Edit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/Edit',
            meta_dot_v1_dot_messenger__pb2.EditRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.EditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unsend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/Unsend',
            meta_dot_v1_dot_messenger__pb2.UnsendRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.UnsendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTyping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/SetTyping',
            meta_dot_v1_dot_messenger__pb2.SetTypingRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SetTypingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/MarkRead',
            meta_dot_v1_dot_messenger__pb2.MarkReadRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.MarkReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessageRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/ListMessageRequests',
            meta_dot_v1_dot_messenger__pb2.ListMessageRequestsRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.ListMessageRequestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListThemes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/ListThemes',
            meta_dot_v1_dot_messenger__pb2.ListThemesRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.ListThemesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindTheme(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/FindTheme',
            meta_dot_v1_dot_messenger__pb2.FindThemeRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.FindThemeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTheme(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/SetTheme',
            meta_dot_v1_dot_messenger__pb2.SetThemeRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SetThemeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/GetCurrentNote',
            meta_dot_v1_dot_messenger__pb2.GetCurrentNoteRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.GetCurrentNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/CreateNote',
            meta_dot_v1_dot_messenger__pb2.CreateNoteRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.CreateNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/DeleteNote',
            meta_dot_v1_dot_messenger__pb2.DeleteNoteRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.DeleteNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecreateNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/RecreateNote',
            meta_dot_v1_dot_messenger__pb2.RecreateNoteRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.RecreateNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRestricted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/SetRestricted',
            meta_dot_v1_dot_messenger__pb2.SetRestrictedRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SetRestrictedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMessageBlocked(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/SetMessageBlocked',
            meta_dot_v1_dot_messenger__pb2.SetMessageBlockedRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SetMessageBlockedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListThreads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/ListThreads',
            meta_dot_v1_dot_messenger__pb2.ListThreadsRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.ListThreadsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/GetThread',
            meta_dot_v1_dot_messenger__pb2.GetThreadRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.GetThreadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePoll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/CreatePoll',
            meta_dot_v1_dot_messenger__pb2.CreatePollRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.CreatePollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VotePoll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/VotePoll',
            meta_dot_v1_dot_messenger__pb2.VotePollRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.VotePollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPinnedMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/ListPinnedMessages',
            meta_dot_v1_dot_messenger__pb2.ListPinnedMessagesRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.ListPinnedMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPollDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/GetPollDetails',
            meta_dot_v1_dot_messenger__pb2.GetPollDetailsRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.GetPollDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/SearchMessages',
            meta_dot_v1_dot_messenger__pb2.SearchMessagesRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SearchMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MuteThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/MuteThread',
            meta_dot_v1_dot_messenger__pb2.MuteThreadRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.MuteThreadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MuteThreadCalls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/MuteThreadCalls',
            meta_dot_v1_dot_messenger__pb2.MuteThreadCallsRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.MuteThreadCallsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetApprovalMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/SetApprovalMode',
            meta_dot_v1_dot_messenger__pb2.SetApprovalModeRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SetApprovalModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetArchived(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/SetArchived',
            meta_dot_v1_dot_messenger__pb2.SetArchivedRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SetArchivedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMessagePinned(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/SetMessagePinned',
            meta_dot_v1_dot_messenger__pb2.SetMessagePinnedRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SetMessagePinnedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetThreadPhoto(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/meta.v1.MessengerService/SetThreadPhoto',
            meta_dot_v1_dot_messenger__pb2.SetThreadPhotoRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SetThreadPhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/DeleteThread',
            meta_dot_v1_dot_messenger__pb2.DeleteThreadRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.DeleteThreadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/CreateDM',
            meta_dot_v1_dot_messenger__pb2.CreateDMRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.CreateDMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/SearchUsers',
            meta_dot_v1_dot_messenger__pb2.SearchUsersRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SearchUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/GetContact',
            meta_dot_v1_dot_messenger__pb2.GetContactRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.GetContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/SetAdmin',
            meta_dot_v1_dot_messenger__pb2.SetAdminRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SetAdminResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetThreadName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/SetThreadName',
            meta_dot_v1_dot_messenger__pb2.SetThreadNameRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SetThreadNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetThreadEmoji(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/SetThreadEmoji',
            meta_dot_v1_dot_messenger__pb2.SetThreadEmojiRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SetThreadEmojiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetNickname(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.MessengerService/SetNickname',
            meta_dot_v1_dot_messenger__pb2.SetNicknameRequest.SerializeToString,
            meta_dot_v1_dot_messenger__pb2.SetNicknameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
