# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from meta.v1 import runtime_pb2 as meta_dot_v1_dot_runtime__pb2


class RuntimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/meta.v1.RuntimeService/GetInfo',
                request_serializer=meta_dot_v1_dot_runtime__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_runtime__pb2.GetInfoResponse.FromString,
                _registered_method=True)


class RuntimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=meta_dot_v1_dot_runtime__pb2.GetInfoRequest.FromString,
                    response_serializer=meta_dot_v1_dot_runtime__pb2.GetInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meta.v1.RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meta.v1.RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.RuntimeService/GetInfo',
            meta_dot_v1_dot_runtime__pb2.GetInfoRequest.SerializeToString,
            meta_dot_v1_dot_runtime__pb2.GetInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
