# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meta/v1/runtime.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'meta/v1/runtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from meta.v1 import common_pb2 as meta_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15meta/v1/runtime.proto\x12\x07meta.v1\x1a\x14meta/v1/common.proto\"\x10\n\x0eGetInfoRequest\"\x95\x01\n\x0fGetInfoResponse\x12\x34\n\x08protocol\x18\x01 \x01(\x0b\x32\x18.meta.v1.ProtocolVersionR\x08protocol\x12(\n\x05\x62uild\x18\x02 \x01(\x0b\x32\x12.meta.v1.BuildInfoR\x05\x62uild\x12\"\n\x0c\x63\x61pabilities\x18\x03 \x03(\tR\x0c\x63\x61pabilities2N\n\x0eRuntimeService\x12<\n\x07GetInfo\x12\x17.meta.v1.GetInfoRequest\x1a\x18.meta.v1.GetInfoResponseB+Z)go.mewis.me/meta.go/gen/go/meta/v1;metav1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meta.v1.runtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)go.mewis.me/meta.go/gen/go/meta/v1;metav1'
  _globals['_GETINFOREQUEST']._serialized_start=56
  _globals['_GETINFOREQUEST']._serialized_end=72
  _globals['_GETINFORESPONSE']._serialized_start=75
  _globals['_GETINFORESPONSE']._serialized_end=224
  _globals['_RUNTIMESERVICE']._serialized_start=226
  _globals['_RUNTIMESERVICE']._serialized_end=304
# @@protoc_insertion_point(module_scope)
