# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from meta.v1 import session_pb2 as meta_dot_v1_dot_session__pb2


class SessionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/meta.v1.SessionService/CreateSession',
                request_serializer=meta_dot_v1_dot_session__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_session__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.Connect = channel.unary_unary(
                '/meta.v1.SessionService/Connect',
                request_serializer=meta_dot_v1_dot_session__pb2.ConnectRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_session__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/meta.v1.SessionService/CloseSession',
                request_serializer=meta_dot_v1_dot_session__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_session__pb2.CloseSessionResponse.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/meta.v1.SessionService/GetHealth',
                request_serializer=meta_dot_v1_dot_session__pb2.GetHealthRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_session__pb2.GetHealthResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/meta.v1.SessionService/SubscribeEvents',
                request_serializer=meta_dot_v1_dot_session__pb2.SubscribeEventsRequest.SerializeToString,
                response_deserializer=meta_dot_v1_dot_session__pb2.SubscribeEventsResponse.FromString,
                _registered_method=True)


class SessionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=meta_dot_v1_dot_session__pb2.CreateSessionRequest.FromString,
                    response_serializer=meta_dot_v1_dot_session__pb2.CreateSessionResponse.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=meta_dot_v1_dot_session__pb2.ConnectRequest.FromString,
                    response_serializer=meta_dot_v1_dot_session__pb2.ConnectResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=meta_dot_v1_dot_session__pb2.CloseSessionRequest.FromString,
                    response_serializer=meta_dot_v1_dot_session__pb2.CloseSessionResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=meta_dot_v1_dot_session__pb2.GetHealthRequest.FromString,
                    response_serializer=meta_dot_v1_dot_session__pb2.GetHealthResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=meta_dot_v1_dot_session__pb2.SubscribeEventsRequest.FromString,
                    response_serializer=meta_dot_v1_dot_session__pb2.SubscribeEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meta.v1.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meta.v1.SessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.SessionService/CreateSession',
            meta_dot_v1_dot_session__pb2.CreateSessionRequest.SerializeToString,
            meta_dot_v1_dot_session__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.SessionService/Connect',
            meta_dot_v1_dot_session__pb2.ConnectRequest.SerializeToString,
            meta_dot_v1_dot_session__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.SessionService/CloseSession',
            meta_dot_v1_dot_session__pb2.CloseSessionRequest.SerializeToString,
            meta_dot_v1_dot_session__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meta.v1.SessionService/GetHealth',
            meta_dot_v1_dot_session__pb2.GetHealthRequest.SerializeToString,
            meta_dot_v1_dot_session__pb2.GetHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/meta.v1.SessionService/SubscribeEvents',
            meta_dot_v1_dot_session__pb2.SubscribeEventsRequest.SerializeToString,
            meta_dot_v1_dot_session__pb2.SubscribeEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
